# Ejercicios de pruebas para validar sintaxis y uso de funciones
# Python ( Mónica Villasuso)

**Variables, listas, diccionarios, condicionales, booleanos, funciones, while**

------------------------------------------------------------------------------------------------------------

## Ejercicio 1.



In [4]:
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}

for word in words:
   letter = word[0]
   if letter not in by_letter:
        by_letter[letter] = [word]
   else:
        by_letter[letter].append(word)

print (by_letter)

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


In [7]:
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)

from collections import defaultdict

by_letter = defaultdict(list)
print(by_letter)
print(words)


for word in words:
    by_letter[word[0]].append(word)
    print(by_letter)

defaultdict(<class 'list'>, {})
['apple', 'bat', 'bar', 'atom', 'book']
defaultdict(<class 'list'>, {'a': ['apple']})
defaultdict(<class 'list'>, {'a': ['apple'], 'b': ['bat']})
defaultdict(<class 'list'>, {'a': ['apple'], 'b': ['bat', 'bar']})
defaultdict(<class 'list'>, {'a': ['apple', 'atom'], 'b': ['bat', 'bar']})
defaultdict(<class 'list'>, {'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']})


In [10]:
strings =['a', 'as', 'bat', 'car', 'dove', 'python']
set(map(len, strings))


{1, 2, 3, 4, 6}

1. Crea una


In [11]:
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n ** 2))
    for i in range(1, n + 1):
        yield i ** 2

In [12]:
squares(8)

<generator object squares at 0x7f81a6fb85d0>

In [15]:
#GENERADORES
gen = squares (8)
for x in gen:
    print(x)

Generating squares from 1 to 64
1
4
9
16
25
36
49
64


#EJEMPLO DE TRY and EXCEPT

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [3]:
import numpy as np
arr = np.arange(4)

print(arr.shape)


print(arr)


(4,)
[0 1 2 3]


In [19]:
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]     # arr[None, :]
row_vec.shape

print(arr.shape)
print(row_vec.shape)

print(arr)
print (row_vec)

print("---------- Multiplica una matriz (2x3) por un vector (1x3)")
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
print(x.shape)
print(np.ones(3))

print( "Result:", np.dot(x, np.ones(3)))



(4,)
(1, 4)
[0 1 2 3]
[[0 1 2 3]]
---------- Multiplica una matriz (2x3) por un vector (1x3)
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[1. 1. 1.]
Result: [ 6. 15.]


In [ ]:
# make it as column vector by inserting an axis along second dimension
In [11]: col_vec = arr[:, np.newaxis]     # arr[:, None]
In [12]: col_vec.shape
Out[12]: (4, 1) 1D array
In [7]: arr = np.arange(4)
In [8]: arr.shape
Out[8]: (4,)

# make it as row vector by inserting an axis along first dimension
In [9]: row_vec = arr[np.newaxis, :]     # arr[None, :]
In [10]: row_vec.shape
Out[10]: (1, 4)

# make it as column vector by inserting an axis along second dimension
In [11]: col_vec = arr[:, np.newaxis]     # arr[:, None]
In [12]: col_vec.shape
Out[12]: (4, 1)

In [35]:

import pandas as pd 

df= pd.DataFrame(np.random.rand(4, 3),
             columns=['foo', 'bar','mon'],
             index=['a', 'b', 'c','d'])
df.index
#print(df)

Index(['a', 'b', 'c', 'd'], dtype='object')

In [36]:
df['bar']

a    0.583708
b    0.484960
c    0.543292
d    0.635982
Name: bar, dtype: float64

In [37]:
df

foo       bar       mon
a  0.841147  0.583708  0.909450
b  0.226415  0.484960  0.184251
c  0.515652  0.543292  0.921053
d  0.160271  0.635982  0.898995

In [40]:
indice = df.index
print(indice)
indice[0]

Index(['a', 'b', 'c', 'd'], dtype='object')


'a'

In [41]:
data_serie = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data_serie

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [43]:
"d" in data_serie

True

In [44]:
data_serie["b"]

0.5

In [45]:
data_serie.items

<bound method Series.items of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [46]:
data_serie["m"] = 1.5

In [47]:
data_serie

a    0.25
b    0.50
c    0.75
d    1.00
m    1.50
dtype: float64

In [48]:
data_serie["m"]

1.5

In [50]:
data_serie[data_serie>=1]

d    1.0
m    1.5
dtype: float64

In [51]:
rng = np.random.RandomState(42)
print (rng)


RandomState(MT19937)


In [52]:
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [53]:
A = rng.randint(10, size=(3, 4))

In [54]:
A

array([[6, 9, 2, 6],
       [7, 4, 3, 7],
       [7, 2, 5, 4]])

In [55]:
df = pd.DataFrame(A, columns=list('QRST'))


In [56]:
df

Q  R  S  T
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [57]:
df.iloc[0]

Q    6
R    9
S    2
T    6
Name: 0, dtype: int64

In [58]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  1 -5  1  1
2  1 -7  3 -2

In [59]:
df['R']

0    9
1    4
2    2
Name: R, dtype: int64

In [60]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -3  0 -7 -3
1  3  0 -1  3
2  5  0  3  2

In [62]:
df 

Q  R  S  T
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [63]:
df.iloc[0, ::2]  # la mitad de los elementos  (pues el step es 2, de la primera fila   (fila cero)

Q    6
S    2
Name: 0, dtype: int64

In [67]:
df.iloc[1, ::3]   # solo el tercer elemento  (porque dice step 3) de la fila 1  

Q    7
T    7
Name: 1, dtype: int64

In [68]:
df - df.iloc[0, ::2]

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  1.0 NaN  1.0 NaN
2  1.0 NaN  3.0 NaN